# Generated by Django 5.1.6 on 2025-02-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100)),
                ('construtora', models.CharField(max_length=100)),
                ('cnpj_instituto', models.CharField(max_length=20)),
                ('cnpj_construtora', models.CharField(max_length=20)),
                ('contrato', models.CharField(max_length=100)),
                ('equipamentos', models.TextField()),
                ('turno', models.CharField(max_length=50)),
                ('relatorio_diario', models.TextField()),
                ('data', models.DateField()),
                ('responsavel_tecnico_obra', models.CharField(max_length=100)),
                ('responsavel_tecnico_fiscalizacao', models.CharField(max_length=100)),
                ('horario_trabalho', models.CharField(max_length=50)),
                ('prazo_obra', models.IntegerField()),
                ('prazo_decorrido', models.IntegerField()),
                ('prazo_restante', models.IntegerField()),
                ('clima', models.CharField(max_length=50)),
                ('pessoal_efetivo', models.TextField()),
                ('servicos_executados', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('descricao_anexo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
