# Generated by Django 5.1.6 on 2025-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_obra_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('nao-iniciada', 'Não Iniciada'), ('em-andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('paralisada', 'Paralisada')], default='nao-iniciada', max_length=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
